#!/bin/bash
#SBATCH -p dlc 
#SBATCH --gres=gpu:4
#SBATCH -N 1
#SBATCH -c 16
#SBATCH -t 72:00:00
#SBATCH --error=%J.mu.out ## stderr file name(The %J will print job ID number)
#SBATCH --output=%J.mu.out ## stdout file name(The %J will print job ID number)    

#FASTA=GNE_homotetramer.fasta
FASTA=GNE_homodimer.fasta

echo "======================================================="
echo "Using sequence file $FASTA"
echo "======================================================="

BASEDIR=/users/dchelouche/nromanenk/rachel
KOSLOFFDIR=/users/kosloff
OUTPUTS=${BASEDIR}/woutputs/${SLURM_JOBID}

mounts="${BASEDIR}:/mount,${KOSLOFFDIR}/alphafold_data:/data,${OUTPUTS}:/outputs,${BASEDIR}/AF_inputs/:/AF_inputs"

RUNOPTS="--model_preset=multimer \
	--num_multimer_predictions_per_model=1 \
	--fasta_paths=/AF_inputs/${FASTA} \
	--output_dir=/outputs --data_dir=/data/ \
	--mgnify_database_path=/data/mgnify/mgy_clusters_2018_12.fa \
	--template_mmcif_dir=/data/pdb_mmcif/mmcif_files/ \
	--max_template_date=2020-05-14 \
	--obsolete_pdbs_path=/data/pdb_mmcif/obsolete.dat \
	--use_gpu_relax=False \
	--bfd_database_path=/data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
	--uniref90_database_path=/data/uniref90/uniref90.fasta \
	--uniclust30_database_path=/data/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
        --pdb_seqres_database_path=/data/pdb_seqres/pdb_seqres.txt \
        --uniprot_database_path=/data/uniprot/uniprot.fasta"

srun bash -c "mkdir $OUTPUTS"

echo "======================================================="
echo "Starting JOB ${SLURM_JOBID} for input ${FASTA}  at $(date)"
echo "======================================================="


srun -l \
    --container-image=${BASEDIR}/AF_image.sqsh \
    --container-mounts=${mounts} \
    --container-workdir=/app/alphafold \
    --no-container-entrypoint \
    python /app/alphafold/run_alphafold.py $RUNOPTS
    
echo "======================================================="
echo "JOB ${SLURM_JOBID} completed at $(date)"
echo "======================================================="


OR_OUTPUTS=${BASEDIR}/or_outputs
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "Alphafold2 output processing at ${SLURM_JOBID}  the time: $(date)"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

# python3 output_name_update.py -i=137783 -p=./woutputs
# python3 output_name_update.py -i=137783 -p=./woutputs -o=./or_outputs
python3 output_name_update.py -i=${SLURM_JOBID} -p=${BASEDIR}/woutputs -o=OR_OUTPUTS

echo "           "
echo "           "
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "Alphafold2 postprocessing completed at time: $(date)"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

